@baseUrl = http://localhost:8080

### 1. Health Check
GET {{baseUrl}}/

### 2. Login Admin (copie le token dans @token ci-dessous)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin123"
}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjEsIklzQWRtaW4iOnRydWUsImV4cCI6MTc4MzI0Nzk3MX0.WRaIujhQo7clhtnqKX775vKYUEFUBF8zsxTF2NUYtG0

### 3. Search Movies (Public - pas de token requis)
GET {{baseUrl}}/search?query=Matrix

### 4. Register New User
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "password123"
}

### 5. Get All Movies (Protégé)
GET {{baseUrl}}/movies
Authorization: Bearer {{token}}

### 5. Get Movie by ID (Protégé)
GET {{baseUrl}}/movies/2
Authorization: Bearer {{token}}

### 6. Create Movie (Protégé)
POST {{baseUrl}}/movies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Diversion",
  "director": "Glenn Ficara",
  "genre": "Thriller",
  "release_year": 2015,
  "description": "relation entre un arnaqueur pro et une apprentie criminelle"
}

### 7. Update Movie (Protégé)
PUT {{baseUrl}}/movies/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Matrix (Updated)",
  "director": "Wachowski Sisters",
  "genre": "Sci-Fi Action",
  "release_year": 1999,
  "description": "Updated description"
}

### 8. Delete Movie (Protégé)
DELETE {{baseUrl}}/movies/2
Authorization: Bearer {{token}}

### 9. Update My Profile (Protégé)
PUT {{baseUrl}}/user/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Admin Updated",
  "email": "admin-updated@example.com",
  "password": "newadminpass123"
}

### 10. Protected Route (Protégé)
GET {{baseUrl}}/protected
Authorization: Bearer {{token}}

### 11. Reset Database (Admin Only - Protégé)
DELETE {{baseUrl}}/reset
Authorization: Bearer {{token}}

### 12. Swagger Docs
GET {{baseUrl}}/swagger/index.html
